// <auto-generated />
using System;
using Domarservice.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domarservice.Migrations
{
    [DbContext(typeof(DomarserviceContext))]
    partial class DomarserviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domarservice.DAL.BookingRequestByCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("RefereeType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("SportType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("BookingRequestsByCompany");
                });

            modelBuilder.Entity("Domarservice.DAL.BookingRequestByReferee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompanyEventId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("RefereeId")
                        .HasColumnType("integer");

                    b.Property<int>("RefereeType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyEventId");

                    b.ToTable("BookingRequestsByReferee");
                });

            modelBuilder.Entity("Domarservice.DAL.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domarservice.DAL.CompanyEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int[]>("RefereeTypes")
                        .HasColumnType("integer[]");

                    b.Property<int>("SportType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyEvents");
                });

            modelBuilder.Entity("Domarservice.DAL.CompanySport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("SportType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanySports");
                });

            modelBuilder.Entity("Domarservice.DAL.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountyType")
                        .HasColumnType("integer");

                    b.Property<int>("RefereeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.ToTable("Countys");
                });

            modelBuilder.Entity("Domarservice.DAL.Referee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Referees");
                });

            modelBuilder.Entity("Domarservice.DAL.RefereeSport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RefereeId")
                        .HasColumnType("integer");

                    b.Property<int>("RefereeType")
                        .HasColumnType("integer");

                    b.Property<int>("SportType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.ToTable("RefereeSports");
                });

            modelBuilder.Entity("Domarservice.DAL.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefereeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Domarservice.DAL.BookingRequestByCompany", b =>
                {
                    b.HasOne("Domarservice.DAL.Company", "RequestingCompany")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domarservice.DAL.Schedule", "Schedule")
                        .WithMany("BookingRequestByCompanys")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestingCompany");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Domarservice.DAL.BookingRequestByReferee", b =>
                {
                    b.HasOne("Domarservice.DAL.CompanyEvent", "CompanyEvent")
                        .WithMany("BookingRequestByReferees")
                        .HasForeignKey("CompanyEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyEvent");
                });

            modelBuilder.Entity("Domarservice.DAL.CompanyEvent", b =>
                {
                    b.HasOne("Domarservice.DAL.Company", null)
                        .WithMany("CompanyEvents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domarservice.DAL.CompanySport", b =>
                {
                    b.HasOne("Domarservice.DAL.Company", null)
                        .WithMany("Sports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domarservice.DAL.County", b =>
                {
                    b.HasOne("Domarservice.DAL.Referee", null)
                        .WithMany("Countys")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domarservice.DAL.RefereeSport", b =>
                {
                    b.HasOne("Domarservice.DAL.Referee", null)
                        .WithMany("Sports")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domarservice.DAL.Schedule", b =>
                {
                    b.HasOne("Domarservice.DAL.Referee", "Referee")
                        .WithMany("Schedules")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("Domarservice.DAL.Company", b =>
                {
                    b.Navigation("CompanyEvents");

                    b.Navigation("Sports");
                });

            modelBuilder.Entity("Domarservice.DAL.CompanyEvent", b =>
                {
                    b.Navigation("BookingRequestByReferees");
                });

            modelBuilder.Entity("Domarservice.DAL.Referee", b =>
                {
                    b.Navigation("Countys");

                    b.Navigation("Schedules");

                    b.Navigation("Sports");
                });

            modelBuilder.Entity("Domarservice.DAL.Schedule", b =>
                {
                    b.Navigation("BookingRequestByCompanys");
                });
#pragma warning restore 612, 618
        }
    }
}
